# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lovish/sem4/graphics/graphics-boilerplate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lovish/sem4/graphics/graphics-boilerplate/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lovish/sem4/graphics/graphics-boilerplate/src/CMakeFiles /home/lovish/sem4/graphics/graphics-boilerplate/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lovish/sem4/graphics/graphics-boilerplate/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphics_asgn1

# Build rule for target.
graphics_asgn1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphics_asgn1
.PHONY : graphics_asgn1

# fast build rule for target.
graphics_asgn1/fast:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/build
.PHONY : graphics_asgn1/fast

ball.o: ball.cpp.o

.PHONY : ball.o

# target to build an object file
ball.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/ball.cpp.o
.PHONY : ball.cpp.o

ball.i: ball.cpp.i

.PHONY : ball.i

# target to preprocess a source file
ball.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/ball.cpp.i
.PHONY : ball.cpp.i

ball.s: ball.cpp.s

.PHONY : ball.s

# target to generate assembly for a file
ball.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/ball.cpp.s
.PHONY : ball.cpp.s

color.o: color.cpp.o

.PHONY : color.o

# target to build an object file
color.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/color.cpp.o
.PHONY : color.cpp.o

color.i: color.cpp.i

.PHONY : color.i

# target to preprocess a source file
color.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/color.cpp.i
.PHONY : color.cpp.i

color.s: color.cpp.s

.PHONY : color.s

# target to generate assembly for a file
color.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/color.cpp.s
.PHONY : color.cpp.s

ground.o: ground.cpp.o

.PHONY : ground.o

# target to build an object file
ground.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/ground.cpp.o
.PHONY : ground.cpp.o

ground.i: ground.cpp.i

.PHONY : ground.i

# target to preprocess a source file
ground.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/ground.cpp.i
.PHONY : ground.cpp.i

ground.s: ground.cpp.s

.PHONY : ground.s

# target to generate assembly for a file
ground.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/ground.cpp.s
.PHONY : ground.cpp.s

input.o: input.cpp.o

.PHONY : input.o

# target to build an object file
input.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/input.cpp.o
.PHONY : input.cpp.o

input.i: input.cpp.i

.PHONY : input.i

# target to preprocess a source file
input.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/input.cpp.i
.PHONY : input.cpp.i

input.s: input.cpp.s

.PHONY : input.s

# target to generate assembly for a file
input.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/input.cpp.s
.PHONY : input.cpp.s

kante.o: kante.cpp.o

.PHONY : kante.o

# target to build an object file
kante.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/kante.cpp.o
.PHONY : kante.cpp.o

kante.i: kante.cpp.i

.PHONY : kante.i

# target to preprocess a source file
kante.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/kante.cpp.i
.PHONY : kante.cpp.i

kante.s: kante.cpp.s

.PHONY : kante.s

# target to generate assembly for a file
kante.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/kante.cpp.s
.PHONY : kante.cpp.s

magnet.o: magnet.cpp.o

.PHONY : magnet.o

# target to build an object file
magnet.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/magnet.cpp.o
.PHONY : magnet.cpp.o

magnet.i: magnet.cpp.i

.PHONY : magnet.i

# target to preprocess a source file
magnet.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/magnet.cpp.i
.PHONY : magnet.cpp.i

magnet.s: magnet.cpp.s

.PHONY : magnet.s

# target to generate assembly for a file
magnet.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/magnet.cpp.s
.PHONY : magnet.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/main.cpp.s
.PHONY : main.cpp.s

nonedit.o: nonedit.cpp.o

.PHONY : nonedit.o

# target to build an object file
nonedit.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/nonedit.cpp.o
.PHONY : nonedit.cpp.o

nonedit.i: nonedit.cpp.i

.PHONY : nonedit.i

# target to preprocess a source file
nonedit.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/nonedit.cpp.i
.PHONY : nonedit.cpp.i

nonedit.s: nonedit.cpp.s

.PHONY : nonedit.s

# target to generate assembly for a file
nonedit.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/nonedit.cpp.s
.PHONY : nonedit.cpp.s

number.o: number.cpp.o

.PHONY : number.o

# target to build an object file
number.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/number.cpp.o
.PHONY : number.cpp.o

number.i: number.cpp.i

.PHONY : number.i

# target to preprocess a source file
number.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/number.cpp.i
.PHONY : number.cpp.i

number.s: number.cpp.s

.PHONY : number.s

# target to generate assembly for a file
number.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/number.cpp.s
.PHONY : number.cpp.s

other_handlers.o: other_handlers.cpp.o

.PHONY : other_handlers.o

# target to build an object file
other_handlers.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/other_handlers.cpp.o
.PHONY : other_handlers.cpp.o

other_handlers.i: other_handlers.cpp.i

.PHONY : other_handlers.i

# target to preprocess a source file
other_handlers.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/other_handlers.cpp.i
.PHONY : other_handlers.cpp.i

other_handlers.s: other_handlers.cpp.s

.PHONY : other_handlers.s

# target to generate assembly for a file
other_handlers.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/other_handlers.cpp.s
.PHONY : other_handlers.cpp.s

pond.o: pond.cpp.o

.PHONY : pond.o

# target to build an object file
pond.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/pond.cpp.o
.PHONY : pond.cpp.o

pond.i: pond.cpp.i

.PHONY : pond.i

# target to preprocess a source file
pond.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/pond.cpp.i
.PHONY : pond.cpp.i

pond.s: pond.cpp.s

.PHONY : pond.s

# target to generate assembly for a file
pond.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/pond.cpp.s
.PHONY : pond.cpp.s

timer.o: timer.cpp.o

.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i

.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s

.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/timer.cpp.s
.PHONY : timer.cpp.s

trampoline.o: trampoline.cpp.o

.PHONY : trampoline.o

# target to build an object file
trampoline.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/trampoline.cpp.o
.PHONY : trampoline.cpp.o

trampoline.i: trampoline.cpp.i

.PHONY : trampoline.i

# target to preprocess a source file
trampoline.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/trampoline.cpp.i
.PHONY : trampoline.cpp.i

trampoline.s: trampoline.cpp.s

.PHONY : trampoline.s

# target to generate assembly for a file
trampoline.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/trampoline.cpp.s
.PHONY : trampoline.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... graphics_asgn1"
	@echo "... ball.o"
	@echo "... ball.i"
	@echo "... ball.s"
	@echo "... color.o"
	@echo "... color.i"
	@echo "... color.s"
	@echo "... ground.o"
	@echo "... ground.i"
	@echo "... ground.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... kante.o"
	@echo "... kante.i"
	@echo "... kante.s"
	@echo "... magnet.o"
	@echo "... magnet.i"
	@echo "... magnet.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... nonedit.o"
	@echo "... nonedit.i"
	@echo "... nonedit.s"
	@echo "... number.o"
	@echo "... number.i"
	@echo "... number.s"
	@echo "... other_handlers.o"
	@echo "... other_handlers.i"
	@echo "... other_handlers.s"
	@echo "... pond.o"
	@echo "... pond.i"
	@echo "... pond.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... trampoline.o"
	@echo "... trampoline.i"
	@echo "... trampoline.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

